services:
  nginx:
    container_name: cake_nginx
    build:
      context: ./docker/nginx
    privileged: true
    command: /sbin/init
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/default.conf:/etc/nginx/default.d/default.conf
      - ../project:/var/www/html
    tty: true
    restart: always
    depends_on:
      - php

  php:
    container_name: cake_php
    build:
      context: ./docker/php
    privileged: true
    command: /sbin/init
    ports:
      - 9000:9000
    volumes:
      - ../project:/var/www/html
    tty: true
    restart: always
    depends_on:
      - mysql

  mysql:
    container_name: cake_mysql
    image: mariadb:10.11.6
    #privileged: true
    #command: /sbin/init
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PW}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PW}
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysqldata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    tty: true
    restart: always

volumes: 
  mysqldata: