services:
  nginx:
    container_name: cake_nginx
    build:
      context: ./docker/nginx
    #privileged: true
    #command: /sbin/init
    ports:
      - 8081:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/default.conf:/etc/nginx/default.d/default.conf
#      - ./docker/nginx/phpmyadmin.conf:/etc/nginx/default.d/phpmyadmin.conf
      - ../project:/var/www/html
    tty: true
    restart: always
    depends_on:
      - php

  php:
    container_name: cake_php
    build:
      context: ./docker/php
    #privileged: true
    #command: /sbin/init
    command:
      php-fpm -F
    ports:
      - 9000:9000
    volumes:
      - ../project:/var/www/html
    tty: true
    restart: always
    depends_on:
      - mysql

  phpmyadmin:
    container_name: cake_phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOSTS: mysql
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PW}
    ports:
      - 8082:80
    depends_on:
      - mysql
    restart: always

  mysql:
    container_name: cake_mysql
    image: mariadb:10.11.6
    #privileged: true
    #command: /sbin/init
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PW}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PW}
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - mysqldata:/var/lib/mysql
      - ./docker/mysql/db:/docker-entrypoint-initdb.d
      #- ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    tty: true
    restart: always

volumes: 
  mysqldata: